[package]
name = "example-lambda-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aws_lambda_events = { version = "0.15.1", features = ["s3", "sqs"] }
lambda_runtime = "0.13.0"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = { version = "1", features = ["macros"] }
